// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetBiere.Entity;

namespace ProjetBiere.Entity.Migrations
{
    [DbContext(typeof(ProjetBiereContext))]
    [Migration("20200127031309_AddEntityFramework")]
    partial class AddEntityFramework
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetBiere.Entity.Biere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("ABV")
                        .HasColumnType("float");

                    b.Property<int>("IBU")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SRM")
                        .HasColumnType("int");

                    b.Property<int>("Saisonniere")
                        .HasColumnType("int");

                    b.Property<int>("Style")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bieres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ABV = 4.2999999999999998,
                            IBU = 53,
                            Nom = "IPA 1",
                            SRM = 4,
                            Saisonniere = 0,
                            Style = 0
                        },
                        new
                        {
                            Id = 2,
                            ABV = 4.2999999999999998,
                            IBU = 53,
                            Nom = "Blanche 1",
                            SRM = 5,
                            Saisonniere = 0,
                            Style = 4
                        },
                        new
                        {
                            Id = 3,
                            ABV = 8.0,
                            IBU = 70,
                            Nom = "IPA 2",
                            SRM = 2,
                            Saisonniere = 1,
                            Style = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
